FROM --platform=linux/x86_64 wirebot/cryptobox:1.4.0 AS test-stage
WORKDIR /app

COPY . ./
WORKDIR /app/backend

# execute tests, store exit code and force success so export stage can copy the test results, evaluating exit status at later stage.
RUN ./mvnw test -Dmaven.test.skip=false 2>&1 || echo $? > /tmp/test.result || echo "Tests failed"

FROM scratch AS export-stage
COPY --from=test-stage /app/backend/target/surefire-reports/TEST-*.xml /tmp/test.result /