apiVersion: v1
kind: Service
metadata:
  name: roman
  labels:
    name: roman
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    name: roman
