apiVersion: v1
kind: Service
metadata:
  app: roman
  labels:
    app: roman
spec:
  type: ClusterIP
  ports:
    - port: 80
      targetPort: 8080
      protocol: TCP
      name: http
  selector:
    app: roman
